### ISSUE TITLE
[BUG]: desynchronized issues and PR templates

### ISSUE THREAD

**Issue by Valentin271** [Libra-foundation/.github#14]
### Steps to Reproduce

1. Create an issue, notice `bug`, `feature` or **`refactor`** type.
2. Create a PR, notice `refactor` is not present as an "official" PR title type.

### Expected Behavior

I'd excpect a _REFACTOR_ PR type to concord with issue type.

### Current behavior

When I create a PR to work on a `refactor` type issue, there is no _REFACTOR_ PR type.

### Checks

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

**Comment by kilian-goetz** [comment]
Hi @Valentin271,

As it's precise in prerequisite part of PR template, the list provided is non-exhaustive. This indeed you can define what you want (only if it's relevant).
